---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tuppr
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/system-upgrade/tuppr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  targetNamespace: system-upgrade
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tuppr-upgrades
  namespace: flux-system
spec:
  dependsOn:
    - name: tuppr
  interval: 1h
  path: ./kubernetes/apps/system-upgrade/tuppr/upgrades
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  targetNamespace: system-upgrade
