apiVersion: v1
kind: Secret
metadata:
    name: glauth-secrets
    namespace: default
    ## sops --encrypt --in-place ./kubernetes/apps/default/lldap/app/lldap.sops.yaml
    ## sops --decrypt ./kubernetes/apps/default/lldap/app/lldap.sops.yaml | kubectl apply -f -
    # Create passbcrypt:
    #   "https://cyberchef.rafaribe.com/#recipe=Bcrypt(12)To_Hex('None',0)"
    # or
    #   htpasswd -bnBC 10 "" YOUR_PASSWORD | tr -d ':\n' | od -A n -t x1 | sed 's/ *//g' | tr -d '\n'
stringData:
    server.toml: ENC[AES256_GCM,data:7nduwGTqcTgvIgE82L/uEdWXyPvE6keSO1u8BZE/ikwjlqRZkFl7ukbIWMKe4zFE5iJ0cClcbhTdWEzQw10P5ZC/3cSvZLTNMwMeEKeG0RPahdbQAbhf69MB8ulxUCvLVAmzrZdxb6CqxgTU9h2e8ygvb7W4sqQ/E9JCzJfBAtUCeW7F0VHcGggLEMgy1WH/QpYbGnDWVYsJwaE4BCFEjiJRBKntaAsk/2rvdhTvegaWOFAQLt4S7InzVJB+dJTdrNoZlNtWYyhL/KTBbf0ZjNbYA+IQ,iv:PvoR3n+SDciAdw+Y3xP3sG7ip4b8p1oiBQlr9CUJOrs=,tag:PV6hBBzCoqIlBNcO+cizUw==,type:str]
    groups.toml: ENC[AES256_GCM,data:SGXmZDDS99cGCsEscbekSZKlzQFbqNt2hVJNlHdjIC3CueI37bR4h2Bf4cJKBAszuB3v0WQl8pAwCEPOzr8nzGy3fejzu9uftcLEzmqPpQWWCEg1GdsXeqFo9hwX6qh82jtWjckGvXCwsGy830fz1Ga7uAU71jQwlsX8ROGzFU3apNeiLI/WYlmbHv1oznG/lJ4=,iv:NTJvylA3V6qlBGn9gJafIBm/UD8cdmM+1bY60OsxJP4=,tag:gDFf4mfdoQ+A1z2E3XWFYA==,type:str]
    users.toml: ENC[AES256_GCM,data:iVCZ5tQQRsnEP4bFVVJqKoRQIN0RjRDCJYLHkjIgemZkEx6oxseLVKWvOLe4IEi3VZpqqk1AUpZlthcB/KpzAo524xYX6aE8kuUBilxnjRtwtBbqKMGOqyCuER5QyECrmHkxY+dNP5rt33fhaUhVbLIO1pVO2FL712BJdjM68GEwIqSmMfy7YrQZzuo4rNUq3yvfNHaM47a3xVD0FbKn8QOlA9B3nVeEh6/SBdluJE5Xnk+qYe4pqLAPyc+ihOer4XChX8Czzseu0/dZkUq6oT0DzSMomM7v+WcNUaGa4iLc2qRs68pPrPZ3PknRIjcLCEGhfQaKXC4fIHt0ZiCyV/EcI/3PF3fHEVfUwSESBEZX7noUyawRJHP4MEg7C6qPTXwA6nVGdOgDltQ9OrwL7bmFT8E3SAgyYBSWnZ9hIOCK9MuCHsgILE18gRnJTVHOvtc6T9tny36SYeQNcStDQ6tQAtIueTptSfTvC/rCfJvAAN7DL6Bg9FkM+qduR0uIU33B2+45YjtgEf9A7G+Ku2CmJe+zwtiJMy/q6rC10feKh3BkER9n+Di18ZlDCABbx2nxsOV82XY3zH8MmpCU4YwQ7C1n0zfjKUvWTeunYD0CvrwMmlb562u/2NRIDbB3ux5lCS2VerSlzLLurb0536evMHuOafASEMCSNqqAfNR5Q+E3oUOABn2IXHeUoZA5SEN/LQKjo4aJ4cc3CmqxfmEGWkPhW0v4uI/YFzgJELJp/VWAbmNNZfGQknXQ3KQsVj6V6v5wRU92upbEEAI=,iv:3MbZASu2R6bKI5c5YqYc0QCubNqPw2NrpRu9WGjfN7M=,tag:k6u5fiy9VoDtLgSccSiwZw==,type:str]
sops:
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNHB6TGNjdlR6OFlmWG1s
            K0ZvK2hyUVRkU3QrenVIZWdZU21oYXUxa0FnCndNL3FpempsV0d5N3poMTFZdXRs
            N1FMT1pNQTcyeXY0bHRNQzliUUVyaXcKLS0tIGU0R1hRejAzT2hycEROb21MMWhL
            QktEZ2F3TlFaeXlLYXdJWURvaXpxNHMKKn+TZy2D4OxznFDETFXceZkcIq08IZpx
            cQqqNxGbiEgEc7Z3zen0ourv1xCFE9/+nDA2PEQVZUuElZCwyv21yA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T18:32:40Z"
    mac: ENC[AES256_GCM,data:Si/Q2/HAjlKAUBqG6hP2QqtyxJXxafH7DuI+xGcYmadCH5iwFsmreXBOwMSEmp3li6g/wwspvrvwEZxtNg8PNIDr48578qQYdOKeVTm6fn3KUl9ffgufXa0+4573tRzeophh8Ol5oqToOU5cqu6iZNqvpTPGpMXtNMSzUbcdH88=,iv:AZgTVfd8Vj2Op1SZsc5zZndPmCAdccALPd3xyDelMJY=,tag:1ofDX6mcevRvr8exiEHCaQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
