---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: it-tools
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: it-tools
  interval: 1h
  path: ./kubernetes/apps/default/it-tools/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  timeout: 5m
