---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname dittofeed-dev-clickhouse
  namespace: flux-system
spec:
  targetNamespace: sensei
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 30m
  timeout: 5m
  path: "./kubernetes/apps/sensei/dittofeed-dev/clickhouse"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
---
# # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &appname dittofeed-dev-temporal
#   namespace: flux-system
# spec:
#   targetNamespace: sensei
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *appname
#   # dependsOn:
#   #   - name: dittofeed-dev-clickhouse
#   interval: 30m
#   timeout: 5m
#   path: "./kubernetes/apps/sensei/dittofeed-dev/temporal"
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: home-kubernetes
#   wait: false
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname dittofeed-dev
  namespace: flux-system
spec:
  targetNamespace: sensei
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  dependsOn:
    # - name: dittofeed-dev-clickhouse
    - name: dittofeed-dev-temporal
  interval: 30m
  timeout: 5m
  path: "./kubernetes/apps/sensei/dittofeed-dev/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false

