---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: ${APP}-dst
  labels:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  trigger:
    manual: restore-once
  kopia:
    copyMethod: Snapshot
    enableFileDeletion: true
    cleanupCachePVC: true
    cleanupTempPVC: true
    repository: ${APP}-volsync-secret
    sourceIdentity:
      sourceName: ${APP}
    capacity: ${VOLSYNC_CAPACITY:=5Gi}
    accessModes: ["${VOLSYNC_ACCESSMODES:=ReadWriteOnce}"]
    storageClassName: ${VOLSYNC_STORAGECLASS:=ceph-block}
    volumeSnapshotClassName: ${VOLSYNC_SNAPSHOTCLASS:=csi-ceph-blockpool}
    moverSecurityContext:
      runAsUser: ${VOLSYNC_UID:=1000}
      runAsGroup: ${VOLSYNC_GID:=1000}
      fsGroup: ${VOLSYNC_GID:=1000}
