---
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  KOPIA_PASSWORD: ${VOLSYNC_KOPIA_PASSWORD}
  KOPIA_FS_PATH: /repository
  KOPIA_REPOSITORY: "filesystem:///repository"
