---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sensei-stage-admin
  namespace: sensei
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 4.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      sensei-stage-admin:
        replicas: 1
        containers:
          app:
            image:
              repository: ghcr.io/clarknova99/project-sensei/admin
              tag: stage-latest@sha256:3ea9e21eae33055e01773859c0c3cdd23317bc7d4b897e9573fc26f4ce424552
              pullPolicy: Always
            env:
              SENSEI_API_KEY: ${SECRET_SENSEI_API_KEY}
              ENVIRONMENT: stage
              PG_URI: postgresql://${SECRET_SENSEI_USERNAME}:${SECRET_SENSEI_PASSWORD}@postgres16vector-rw.database.svc.cluster.local:5432/sensei-stage
              ADMIN_USERNAME: ${SECRET_SENSEI_ADMIN_USERNAME}
              ADMIN_PASSWORD: ${SECRET_SENSEI_ADMIN_PASSWORD}
              SESSION_SECRET: ${SECRET_SENSEI_API_KEY}
              DITTOFEED_AUTH_HEADER: ${SECRET_DITTOFEED_DEV_AUTH_HEADER}
              DITTOFEED_ADMIN_ENDPOINT: https://dittofeed-dev.${SECRET_DOMAIN_TWO}/api/admin/
              DITTOFEED_PAGE_ENDPOINT: https://dittofeed-dev.${SECRET_DOMAIN_TWO}/api/public/apps/page
              DITTOFEED_TRACK_ENDPOINT: https://dittofeed-dev.${SECRET_DOMAIN_TWO}/api/public/apps/track
              DITTOFEED_IDENTIFY_ENDPOINT: https://dittofeed-dev.${SECRET_DOMAIN_TWO}/api/public/apps/identify
              BACKEND_API_URL: http://sensei-stage-api.sensei.svc.cluster.local:3001
              BACKEND_API_KEY: ${SECRET_SENSEI_API_KEY}
              DITTOFEED_WORKSPACE_ID: ${SECRET_DITTOFEED_DEV_WORKSPACE_ID}
              DITTOFEED_ADMIN_TOKEN: ${SECRET_DITTOFEED_DEV_ADMIN_TOKEN}
        pod:
          # imagePullPolicy: Always
          imagePullSecrets:
            - name: sensei-secret
    service:
      app:
        controller: sensei-stage-admin
        ports:
          http:
            port: &port 3002
    route:
      main:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: "Sensei Admin"
          gethomepage.dev/icon: https://senseichess.com/static/images/knight2.svg
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        hostnames:
          - admin-stage.${SECRET_DOMAIN_TWO}
        rules:
          - backendRefs:
              - name: sensei-stage-admin
                port: *port
