---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app dittofeed-dev
  namespace: sensei
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 4.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      dittofeed-dev:
        containers:
          app:
            image:
              repository: dittofeed/dittofeed-lite
              tag: v0.23.0
            env:
              PASSWORD: ${SECRET_SENSEI_PASSWORD}
              SECRET_KEY: ${SECRET_OAUTH_CLIENT_SECRET}
              WORKSPACE_NAME: sensei
              NODE_ENV: production
              AUTH_MODE: single-tenant
              SESSION_COOKIE_SECURE: true
              DASHBOARD_API_BASE: https://dittofeed-dev.${SECRET_DOMAIN_TWO}
              DASHBOARD_URL: https://dittofeed-dev.${SECRET_DOMAIN_TWO}
              TEMPORAL_ADDRESS: dittofeed-dev-temporal.sensei.svc.cluster.local:7233
              DATABASE_HOST: postgres-lb-vector.database.svc.cluster.local
              DATABASE_USER: ${SECRET_PGADMIN_USER}
              DATABASE_PASSWORD: ${SECRET_PGADMIN_PASSWORD}
              DATABASE_URL: postgresql://${SECRET_PGADMIN_USER}:${SECRET_PGADMIN_PASSWORD}@postgres-lb-vector.database.svc.cluster.local:5432/dittofeed_dev
              CLICKHOUSE_HOST: http://dittofeed-dev-clickhouse.sensei.svc.cluster.local:8123
              CLICKHOUSE_USER: dittofeed
              CLICKHOUSE_PASSWORD: ${SECRET_CLICKHOUSE_PASSWORD}
    service:
      app:
        controller: dittofeed-dev
        ports:
          http:
            port: &port 3000
    route:
      main:
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN_TWO}
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Sensei
          gethomepage.dev/icon: https://cdn.prod.website-files.com/664393f5bd2b0c6d4fdf5437/6644bdae62ceb2dabadadb5b_Group%2022.svg
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        hostnames:
          - dittofeed-dev.${SECRET_DOMAIN_TWO}
        rules:
          - backendRefs:
              - name: *app
                port: *port    # ingress:
    #   app:
    #     annotations:
    #       external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN_TWO}"
    #       nginx.ingress.kubernetes.io/proxy-connect-timeout: "240"
    #       nginx.ingress.kubernetes.io/proxy-read-timeout: "240"
    #       nginx.ingress.kubernetes.io/proxy-send-timeout: "240"
    #       hajimari.io/enable: "true"
    #       hajimari.io/icon: mdi:water-flow
    #     className: external
    #     hosts:
    #       - host: dittofeed-dev.${SECRET_DOMAIN_TWO}
    #         paths:
    #           - path: /
    #             pathType: Prefix
    #             service:
    #               identifier: app
    #               port: 3000
    #     tls:
    #       - hosts:
    #           - dittofeed-dev.${SECRET_DOMAIN}
