apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-postgres-exporter
  namespace: prometheus
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus-postgres-exporter
      version: 7.3.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
  # https://artifacthub.io/packages/helm/prometheus-community/prometheus-postgres-exporter
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-postgres-exporter/values.yaml

  # postgresql://${SECRET_SENSEI_USERNAME}:${SECRET_SENSEI_PASSWORD}@postgres16vector-rw.database.svc.cluster.local:5432/sensei-prod
    serviceMonitor:
      enabled: true
    config:
      datasource:
        host: postgres16vector-rw.database.svc.cluster.local
        port: "5432"
        user: ${SECRET_SENSEI_USERNAME}
        password: ${SECRET_SENSEI_PASSWORD}
        database: sensei-prod
    tolerations:
    - effect: NoSchedule
      key: CriticalAddonsOnly
      operator: Equal
      value: "true"
