---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rybbit-clickhouse
  namespace: flux-system
spec:
  targetNamespace: sensei
  commonMetadata:
    labels:
      app.kubernetes.io/name: rybbit-clickhouse
  interval: 30m
  timeout: 5m
  path: "./kubernetes/apps/sensei/rybbit/clickhouse"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rybbit
  namespace: flux-system
spec:
  targetNamespace: sensei
  commonMetadata:
    labels:
      app.kubernetes.io/name: rybbit
  dependsOn:
    - name: cloudnative-pg-cluster3
    - name: rybbit-clickhouse
  path: ./kubernetes/apps/sensei/rybbit/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 1m
