---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
    kustomize.toolkit.fluxcd.io/substitute: enabled
data:
  kubernetes.yaml: |
    mode: cluster
    gateway: true
    ingress: false
    traefik: false
  settings.yaml: |
    # https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/ICONS.md
    # https://pictogrammers.com/library/mdi/
    # https://simpleicons.org/
    title: Dashboard
    favicon: https://github.com/walkxcode/dashboard-icons/blob/main/png/heimdall.png
    theme: dark
    headerStyle: clean
    #hideVersion: true
    #showStats: true
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
    layout:
      Internal:
        style: row
        columns: 3
        header: false
      Media:
        style: row
        columns: 2
        icon: mdi-play-circle
      Observability:
        style: column
        icon: mdi-monitor-eye
      Infrastructure:
        style: column
        icon: mdi-server-network
      Storage:
        style: column
        icon: mdi-database
      System:
        style: row
        columns: 4
        icon: mdi-application
      Sensei Services:
        style: row
        columns: 3
        header: false
      Sensei Apps:
        style: row
        columns: 2
        icon: mdi-chess-rook
        Sensei App:
          style: row
          columns: 1
          header: false
        Sensei Admin:
          style: row
          columns: 1
          header: false

  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Social:
        - Discord:
            - icon: discord.png
              href: https://discord.com/app
        - Gmail:
            - icon: gmail.png
              href: http://gmail.com
        - Reddit:
            - icon: reddit.png
              href: https://reddit.com
        - Twitch:
            - icon: twitch.png
              href: https://twitch.tv
        - YouTube:
            - icon: youtube.png
              href: https://youtube.com/feed/subscriptions
    - Cloud:
        - CloudFlare:
            - icon: cloudflare.png
              href: https://dash.cloudflare.com
        - AWS Console:
            - icon: aws.png
              href: https://aws.amazon.com/console/
    - Git:
        - Kubesearch:
            - icon: kubernetes-dashboard.png
              description: Helm Chart Search
              href: https://nanne.dev/k8s-at-home-search/
        - Homepage Icons:
            - icon: si-jpeg
              href: https://github.com/homarr-labs/dashboard-icons/blob/main/ICONS.md
        - Homepage MDI:
            - icon: si-materialdesign
              href: https://pictogrammers.com/library/mdi/
        - Homepage SI:
            - icon: si-simpleicons
              href: https://simpleicons.org/
  services.yaml: |
    ---
    - Internal:
        - Adguard:
            icon: adguard-home.svg
            href: https://adguard.${SECRET_DOMAIN_THREE}
            widget:
              type: adguard
              url: https://adguard.${SECRET_DOMAIN_THREE}
              username: ${SECRET_MQTT_USERNAME}
              password: ${SECRET_MQTT_PASSWORD}
        - DS1513+:
            icon: synology-dsm.svg
            href: https://192.168.1.2:5001
            widget:
              type: diskstation
              url: https://192.168.1.2:5001
              username: ${SECRET_CAM_USERNAME}
              password: ${SECRET_MQTT_PASSWORD}
        - DS1522+:
            icon: synology.svg
            href: https://192.168.1.3:5001
            widget:
              type: diskstation
              url: https://192.168.1.3:5001
              username: ${SECRET_MQTT_USERNAME}
              password: ${SECRET_DS1522_PASSWORD}
  widgets.yaml: |
    - search:
        provider: [google]
        focus: false
        target: _blank
    - kubernetes:
        cluster:
          cpu: true
          label: cluster
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: true
          showLabel: true
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
  docker.yaml: ""
