# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  # - ./dittofeed/ks.yaml
  - ./dittofeed-dev/ks.yaml
  # - ./gatus/ks.yaml
  - ./grafana/ks.yaml
  - ./langfusev3/ks.yaml
  - ./langfuse-dev/ks.yaml
  - ./litellm/ks.yaml
  - ./litellm-dev/ks.yaml
  - ./n8n/ks.yaml
  - ./rybbit/ks.yaml
  - ./sensei-prod/ks.yaml
  - ./sensei-stage/ks.yaml
  - ./sensei-dev/ks.yaml
